import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Starting safe reset of demo data...");

  // Safety filter: Identify demo accounts strictly by domain "@demo.ccp.test"
  const demoUsers = await prisma.user.findMany({
    where: {
      email: {
        endsWith: "@demo.ccp.test",
        mode: "insensitive",
      },
    },
    select: { id: true, email: true },
  });

  const demoUserIds = demoUsers.map((u) => u.id);
  console.log(`Found ${demoUserIds.length} demo users to reset.`);

  if (demoUserIds.length === 0) {
    console.log("No demo data found to remove.");
    return;
  }

  // Identify demo projects
  const demoProjects = await prisma.project.findMany({
    where: {
      title: {
        in: ["Project Alpha", "Project Beta"],
      },
    },
    select: { id: true },
  });
  const demoProjectIds = demoProjects.map((p) => p.id);

  // Run cleanup in a strict, safe transaction
  await prisma.$transaction(async (tx) => {
    // 1. Delete notifications for demo users/memberships
    await tx.notification.deleteMany({
      where: {
        OR: [
          { recipientUserId: { in: demoUserIds } },
          { recipientMembership: { userId: { in: demoUserIds } } },
        ],
      },
    });

    // 2. Delete audit events generated by demo actors
    await tx.auditEvent.deleteMany({
      where: {
        actorId: { in: demoUserIds },
      },
    });

    // 3. Delete flags on messages in demo conversations
    await tx.flag.deleteMany({
      where: {
        message: {
          conversation: {
            projectId: { in: demoProjectIds },
          },
        },
      },
    });

    // 4. Delete messages in demo conversations
    await tx.message.deleteMany({
      where: {
        conversation: {
          projectId: { in: demoProjectIds },
        },
      },
    });

    // 5. Delete read states in demo conversations
    await tx.readState.deleteMany({
      where: {
        conversation: {
          projectId: { in: demoProjectIds },
        },
      },
    });

    // 6. Delete conversations for demo projects
    await tx.conversation.deleteMany({
      where: {
        projectId: { in: demoProjectIds },
      },
    });

    // 7. Delete memberships for demo projects
    await tx.membership.deleteMany({
      where: {
        OR: [
          { userId: { in: demoUserIds } },
          { projectId: { in: demoProjectIds } },
        ],
      },
    });

    // 8. Delete demo projects
    await tx.project.deleteMany({
      where: {
        id: { in: demoProjectIds },
      },
    });

    // 9. Delete sessions for demo users
    await tx.session.deleteMany({
      where: {
        userId: { in: demoUserIds },
      },
    });

    // 10. Delete demo users
    const deleted = await tx.user.deleteMany({
      where: {
        id: { in: demoUserIds },
      },
    });

    console.log(`Deleted ${deleted.count} demo users and associated demo resources.`);
  });

  console.log("Demo data reset completed successfully. Non-demo data was strictly untouched.");
}

main()
  .catch((e) => {
    console.error("Demo reset failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

export {};
